<script>
import { Api } from '@/lib/api.js';
import { Webrtc } from '@/lib/webrtc.js';
export default {
  data() {
    return {
        token : '',
        room: "123456789",
    };
  },
  methods : {
    showModal() {
        this.$bvModal.show('modal-token')
    },
    hideModal() {
        this.$bvModal.hide('modal-token')
    },
    Validate(){
        let valid = Api.validate()
        if(valid){
            Webrtc.iamHost()
        }else{
            alert("salah token lu")
        }
    }
  }
};
</script>

<template>
    <div>
        <div class="d-flex flex-column p-2 justify-content-center align-items-center">
            <h4 class="text-dark font-size-18">Room ID : {{room}}</h4>
            <h3 class="mt-2">Waiting approval</h3>
            <p class="mt-1">Please wait, the meeting host will let you in soon.</p>
        </div>
        <div class="form p-2">
            <button @click="showModal()" class="btn btn-light btn-lg btn-block">
                HAVE A HOST TOKEN ?
            </button>
        </div>
        <b-modal id="modal-token" centered no-close-on-backdrop no-close-on-esc  title="Host Token"
            ref="modal-token"
            :hide-header="true"
            :hide-footer="false"
            size="md"
            :hide-header-close="true">
            <div class="p-3">
                <p>The host token is generated by the admin who made this room meeting. if you join the token room from the admin, then you will automatically be hosted in this room meeting.</p>
                <div class="form-group">
                    <label class="control-label">Host Token</label>
                    <input type="text" class="form-control" v-model="token">
                </div>
                <b-button @click="hideModal()">Close</b-button>
                <b-button @click="Validate()">Validate</b-button>
            </div>
        </b-modal>
    </div>
</template>
